name: confido_demo

profile: default

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "seeds"
  - "dbt_packages"

models:
  +static_analysis: baseline
  +materialized: table

  confido_demo: # Folder-level configs
    staging:
      +materialized: view
